// Auto-generated by configure-network.bat
// Generated on: Sat 03/14/2026  9:09:08.83

class NetworkConfig {
  static const String localIP = '192.168.1.138';
  static const String backendUrl = 'https://senyamtikaback-production.up.railway.app/api';
  static const String healthUrl = 'https://senyamtikaback-production.up.railway.app/health';
}
